import { useEffect } from "react";
import { Moon, Shield, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";

const SECTIONS: { title: string; body: React.ReactNode }[] = [
  {
    title: "Overview",
    body: (
      <>
        <p>
          Dreamiric ("we", "our", or "us") is an AI-powered dream journal that lets you record dreams via text or
          voice, receive AI-generated analysis, and explore recurring patterns. This Privacy Policy explains what
          information we collect, how we use it, and the choices you have.
        </p>
        <p>
          By using Dreamiric, you agree to the practices described in this policy. If you do not agree, please do not
          use the app.
        </p>
      </>
    ),
  },
  {
    title: "Information We Collect",
    body: (
      <>
        <p className="font-medium text-foreground">Account information</p>
        <p>
          When you create an account we collect your email address and a securely hashed password (or your Google
          account profile — name, email, and profile picture — if you sign in with Google). We never see or store your
          Google password.
        </p>
        <p className="font-medium text-foreground">Dream content</p>
        <p>
          The dreams you write or dictate (including voice recordings and transcriptions), the AI-generated analyses,
          symbols, images, and chat conversations you have about your dreams, and metadata such as timestamps and mood
          tags.
        </p>
        <p className="font-medium text-foreground">Payment information</p>
        <p>
          If you subscribe to Dreamiric Pro, payments are processed by our payment provider (Razorpay). We receive a
          record of your subscription status and plan, but we never see or store your full card details, UPI
          credentials, or other payment instruments.
        </p>
        <p className="font-medium text-foreground">Usage and device data</p>
        <p>
          Basic technical information such as your device type, operating system, app version, and notification
          preferences, used to keep the app working reliably.
        </p>
      </>
    ),
  },
  {
    title: "How We Use Your Information",
    body: (
      <>
        <p>We use the information we collect to:</p>
        <ul>
          <li>Provide the core journal — storing, displaying, and transcribing your dream entries.</li>
          <li>Generate AI analyses, symbolic interpretations, pattern insights, and dream chat responses.</li>
          <li>Manage your account, subscription, and free-tier limits.</li>
          <li>Send you optional morning reminders and service notifications (only if you enable them).</li>
          <li>Maintain security, prevent abuse, and comply with legal obligations.</li>
        </ul>
        <p>
          We do <strong>not</strong> sell your personal information, and we do not use your dream content for
          advertising or to train models that other users interact with.
        </p>
      </>
    ),
  },
  {
    title: "AI Processing",
    body: (
      <>
        <p>
          Dream analyses, pattern insights, images, and chat replies are generated by third-party AI services acting on
          our behalf. When you request an analysis or send a chat message, the relevant dream text is sent to those
          services solely to generate your result. We instruct these providers not to use your content for their own
          purposes.
        </p>
      </>
    ),
  },
  {
    title: "Data Sharing",
    body: (
      <>
        <p>We share data only with the service providers required to run Dreamiric:</p>
        <ul>
          <li>
            <strong>Hosting and database provider</strong> — stores your account and journal data with
            row-level security so only you can read your entries.
          </li>
          <li>
            <strong>AI service providers</strong> — process dream text to produce your analyses and replies.
          </li>
          <li>
            <strong>Payment processor (Razorpay)</strong> — processes Pro subscription payments.
          </li>
          <li>
            <strong>Push notification services</strong> — deliver reminders if you opt in.
          </li>
        </ul>
        <p>
          We may also disclose information if required by law, or to protect the rights, property, or safety of
          Dreamiric, our users, or others.
        </p>
      </>
    ),
  },
  {
    title: "Data Security",
    body: (
      <>
        <p>
          Your journal is protected by strict access controls: dream entries are governed by row-level security rules
          that restrict every read and write to your own account. Data is transmitted over encrypted connections, and
          access within our team is limited to what is necessary to operate and support the service. No system is
          perfectly secure, but we take safeguarding your most private thoughts seriously.
        </p>
      </>
    ),
  },
  {
    title: "Data Retention & Deletion",
    body: (
      <>
        <p>
          Your dreams are retained for as long as your account is active. You can delete individual entries at any
          time from within the app. If you wish to delete your account and all associated data — including every dream,
          recording, and analysis — contact us using the details below and we will delete it for you.
        </p>
        <p>
          Deleting the app from your device does not delete your account data; use the in-app options or contact us to
          have your data removed.
        </p>
      </>
    ),
  },
  {
    title: "Your Rights",
    body: (
      <>
        <p>Depending on where you live, you may have the right to:</p>
        <ul>
          <li>Access the personal data we hold about you.</li>
          <li>Correct inaccurate data.</li>
          <li>Delete your data and account.</li>
          <li>Object to or restrict certain processing.</li>
          <li>Withdraw consent (for example, disabling notifications).</li>
        </ul>
        <p>To exercise any of these rights, contact us at the email address below.</p>
      </>
    ),
  },
  {
    title: "Children's Privacy",
    body: (
      <>
        <p>
          Dreamiric is not directed at children under 13 (or the equivalent minimum age in your jurisdiction), and we
          do not knowingly collect personal information from them. If you believe a child has created an account,
          contact us and we will remove it.
        </p>
      </>
    ),
  },
  {
    title: "Changes to This Policy",
    body: (
      <>
        <p>
          We may update this Privacy Policy from time to time. When we do, we will revise the "Last updated" date on
          this page. Significant changes will be communicated within the app. Continued use of Dreamiric after an
          update constitutes acceptance of the revised policy.
        </p>
      </>
    ),
  },
  {
    title: "Contact Us",
    body: (
      <>
        <p>
          Questions, requests, or concerns about this policy or your data? Reach us at{" "}
          <a href="mailto:support@dreamiric.com" className="text-primary underline underline-offset-4">
            support@dreamiric.com
          </a>
          .
        </p>
      </>
    ),
  },
];

export default function PrivacyPolicy() {
  const navigate = useNavigate();

  useEffect(() => {
    document.title = "Privacy Policy | Dreamiric";
    return () => {
      document.title = "Dreamiric — Decode Your Subconscious Mind";
    };
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
      {/* Ambient background */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[10%] left-[15%] w-[500px] h-[500px] rounded-full bg-primary/[0.04] blur-[100px]" />
        <div className="absolute bottom-[20%] right-[10%] w-[400px] h-[400px] rounded-full bg-accent/[0.04] blur-[100px]" />
      </div>

      {/* NAV */}
      <nav className="relative z-20 flex items-center justify-between max-w-6xl mx-auto px-6 py-5">
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center">
            <Moon className="w-4.5 h-4.5 text-primary" />
          </div>
          <span className="font-display text-lg font-semibold text-foreground tracking-tight">Dreamiric</span>
        </div>
        <Button
          variant="ghost"
          onClick={() => navigate("/")}
          className="gap-2 font-body text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Button>
      </nav>

      {/* CONTENT */}
      <main className="relative z-10 max-w-3xl mx-auto px-6 pt-10 pb-24">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 mb-6">
            <Shield className="w-3.5 h-3.5 text-primary" />
            <span className="text-xs font-body font-medium text-primary">Your privacy, protected</span>
          </div>
          <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground tracking-tight mb-4">
            Privacy Policy
          </h1>
          <p className="text-sm text-muted-foreground font-body">
            Last updated: {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}
          </p>
        </div>

        <div className="space-y-4">
          {SECTIONS.map((section, i) => (
            <section
              key={section.title}
              className="rounded-2xl bg-card/60 border border-border/40 backdrop-blur-sm p-6 md:p-8 space-y-4 animate-dream-in"
              style={{ animationDelay: `${Math.min(i, 8) * 60}ms` }}
            >
              <h2 className="font-display text-lg md:text-xl font-semibold text-foreground">{section.title}</h2>
              <div className="space-y-3 text-sm text-muted-foreground font-body leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2 [&_strong]:text-foreground [&_p.font-medium]:text-foreground">
                {section.body}
              </div>
            </section>
          ))}
        </div>
      </main>

      {/* FOOTER */}
      <footer className="relative z-10 border-t border-border/30 py-8">
        <div className="max-w-6xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Moon className="w-4 h-4 text-primary" />
            <span className="font-display text-sm font-semibold text-foreground">Dreamiric</span>
          </div>
          <p className="text-xs text-muted-foreground font-body">
            © {new Date().getFullYear()} Dreamiric. Your dreams, your insights, your privacy.
          </p>
        </div>
      </footer>
    </div>
  );
}
